apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: istio
subjects:
- kind: ServiceAccount
  name: default
  namespace: istio
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

