apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - name: grpc-web
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    version: v1
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
      - name: server
        image: grpc-server:latest
        imagePullPolicy: Never
        command: [ "sh", "-c" ]
        args: [ "/bin/server -tls -cert=/etc/secrets/certs/tls.crt -key=/etc/secrets/certs/tls.key" ]
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "100m"
            memory: 1Gi
        volumeMounts:
          - mountPath: /etc/secrets/certs
            name: certs
      volumes:
        - name: certs
          secret:
            secretName: tls-secret
